-- ============================================================
-- 012 — customers, their care notes, and their flags
--
-- The first table holding data about people who never agreed to be in
-- a database. A customer gives a salon their phone number to book a
-- haircut; everything else in here is something the salon wrote down
-- about them afterwards. That difference is why this migration is
-- shaped the way it is.
--
-- THE PROBLEM THIS MIGRATION SOLVES
--
-- DECISIONS #9 commits to field-level permissions: a stylist sees a
-- customer's allergies and not their outstanding balance. Every other
-- table in this project has enforced that kind of rule with column
-- grants — "RLS hides rows, grants hide columns."
--
-- That tool does not reach here. A grant is granted to a POSTGRES
-- role, and every logged-in member of staff — owner, receptionist,
-- stylist — connects as the same one, `authenticated`. A column grant
-- can say "all staff" or "no staff". It cannot say "stylists yes,
-- receptionists no", which is the entire requirement.
--
-- So the sensitive fields move to their own table, where the rule
-- becomes a row-level policy and `has_permission()` can be asked
-- directly. Field-level becomes row-level, using machinery that
-- already exists and is already tested.
--
-- customer_flags was always going to work this way — it carries a
-- min_permission per row precisely so each flag can have its own
-- visibility. This makes the whole customer record one idea instead
-- of two competing ones. See DECISIONS #27.
--
-- No anon grants appear anywhere below. The public booking form does
-- not write to these tables directly; it will go through
-- createAppointment(), the one canonical path. A public insert
-- privilege on customers would be a hole a booking form does not need.
--
-- REGENERATE THE TYPES after this runs:  npx supabase gen types
--   typescript --linked --schema public > src/lib/supabase/database.types.ts
-- ============================================================


-- ------------------------------------------------------------
-- 1. customers.
--
-- No profile_id, no user_id, no password. Customers never log in —
-- DECISIONS #8. They are found or created by phone number at booking
-- time, which is what makes `phone` the load-bearing column here.
--
-- `notes` is one free-text field for things like "parks round the
-- back". It is not the internal notes system PROJECT.md excludes from
-- v1 — that is threads, authors and timestamps, and none of it is
-- here.
--
-- first_visit_at and last_visit_at are maintained by whatever writes
-- appointments, not by hand. They are nullable because a customer
-- created by a booking has not visited yet.
-- ------------------------------------------------------------
create table public.customers (
  id                     uuid primary key default gen_random_uuid(),
  org_id                 uuid not null references public.organizations (id),
  full_name              text not null,
  phone                  text not null,

  -- The matching key. Computed by Postgres, never written by hand —
  -- see the index below for why that distinction is the whole point.
  phone_digits           text generated always as
                           (regexp_replace(phone, '[^0-9]', '', 'g')) stored,

  email                  text,
  birthday               date,
  notes                  text,
  preferred_employee_id  uuid,
  first_visit_at         timestamptz,
  last_visit_at          timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  deleted_at             timestamptz,

  -- A customer's preferred stylist must work at the same salon.
  -- DECISIONS #21: RLS says which rows you may read, not which rows
  -- you may point at.
  constraint customers_preferred_employee_same_org
    foreign key (preferred_employee_id, org_id)
      references public.employees (id, org_id),

  -- Lets customer_care_notes, customer_flags and later appointments
  -- reference this table the same way.
  constraint customers_id_org_key unique (id, org_id)
);

comment on table public.customers is
  'People who get their hair done. No login, ever. Matched by phone number at booking time.';

comment on column public.customers.phone is
  'As the customer gave it, punctuation and all. Displayed and dialled. Not the matching key.';

comment on column public.customers.phone_digits is
  'phone with every non-digit stripped. Generated by Postgres, so it cannot disagree with phone. This is what uniqueness is enforced on.';

comment on column public.customers.notes is
  'One free-text field for operational detail. Not an internal notes system — that is out of v1.';

-- One phone number, one customer, per salon. This is what stops the
-- booking form creating a second Sara every time she books.
--
-- WHY THIS INDEXES phone_digits AND NOT phone
--
-- Uniqueness on the raw string would compare punctuation. These are
-- one person and four rows:
--
--   +1 (202) 555-0143      +1 202 555 0143
--   +12025550143           +1-202-555-0143
--
-- A tidy input box in the booking form would fix all four. It would
-- also be a rule that lives in a browser, and the database has never
-- heard of it — a receptionist pasting from WhatsApp, an import, or
-- someone typing into the SQL editor writes whatever it likes. Same
-- argument as DECISIONS #2: the UI is a suggestion, the database is a
-- guarantee.
--
-- A generated column is computed by Postgres on every single write, so
-- all four collapse to 12025550143 and the second insert is refused —
-- by the database, not by anyone's discipline.
--
-- WHAT IT DELIBERATELY DOES NOT DO
--
-- It strips punctuation. It does not invent a country code. "202 555
-- 0143" and "+1 202 555 0143" are still two different customers, and
-- that is correct here: teaching the database that a ten-digit number
-- is American would hardcode one country into a multi-tenant schema.
--
-- Adding the dial code is the application's job, from the
-- organization's own setting, in one helper that every write path
-- calls. That arrives with the booking form.
create unique index customers_org_phone_key
  on public.customers (org_id, phone_digits)
  where deleted_at is null;

-- Deliberately no uniqueness on full_name or email. Families share
-- both, and a salon may not refuse the second sister.
create index customers_org_id_idx on public.customers (org_id);

create index customers_preferred_employee_id_idx
  on public.customers (preferred_employee_id);

create trigger customers_set_updated_at
  before update on public.customers
  for each row execute function public.set_updated_at();

alter table public.customers enable row level security;


-- ------------------------------------------------------------
-- 2. customer_care_notes — the sensitive half of the record.
--
-- Allergies, sensitivities and the hair formula. Split out for the
-- reason in the header: these need a different audience from the rest
-- of the record, and a separate table is how this database already
-- expresses "different audience".
--
-- One live row per customer. It is a separate table, not a repeating
-- list — the unique index below is what makes that true.
--
-- Not to be confused with customers.notes, which is general and
-- operational. If you can see the customer at all you can see that
-- one. This table needs customer.view_sensitive.
-- ------------------------------------------------------------
create table public.customer_care_notes (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references public.organizations (id),
  customer_id    uuid not null,
  allergies      text,
  sensitivities  text,
  hair_formula   text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,

  constraint customer_care_notes_customer_same_org
    foreign key (customer_id, org_id)
      references public.customers (id, org_id)
);

comment on table public.customer_care_notes is
  'Allergies, sensitivities and hair formula. A separate table because these need a different audience from the rest of the customer record. See DECISIONS #27.';

create unique index customer_care_notes_customer_key
  on public.customer_care_notes (customer_id)
  where deleted_at is null;

create index customer_care_notes_org_id_idx
  on public.customer_care_notes (org_id);

create trigger customer_care_notes_set_updated_at
  before update on public.customer_care_notes
  for each row execute function public.set_updated_at();

alter table public.customer_care_notes enable row level security;


-- ------------------------------------------------------------
-- 3. customer_flags — internal labels, each with its own audience.
--
-- "Prefers morning appointments" is a preference anyone at the desk
-- should see. "Staff Safety Alert" and "Outstanding Balance" are not.
-- Rather than hardcode which is which, every flag carries the
-- permission key required to see it, and the policy asks
-- has_permission() with that value.
--
-- min_permission REFERENCES permissions (key), so it can only ever
-- hold a key that exists. Without that constraint a typo produces a
-- flag no one on earth can read — including the owner — and nothing
-- reports it as an error.
-- ------------------------------------------------------------
create table public.customer_flags (
  id              uuid primary key default gen_random_uuid(),
  org_id          uuid not null references public.organizations (id),
  customer_id     uuid not null,
  flag_type       text not null,
  note            text,
  created_by      uuid,
  min_permission  text not null default 'customer.view'
                    references public.permissions (key),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz,

  constraint customer_flags_customer_same_org
    foreign key (customer_id, org_id)
      references public.customers (id, org_id),

  -- Whoever added the flag must work at the same salon. Nullable, and
  -- a composite foreign key containing a null is not checked, so a
  -- flag added by a script with no acting profile stays legal.
  constraint customer_flags_created_by_same_org
    foreign key (created_by, org_id)
      references public.profiles (id, org_id)
);

comment on column public.customer_flags.min_permission is
  'The permission key required to see this flag. Default customer.view means everyone who can see the customer can see it.';

comment on column public.customer_flags.flag_type is
  'Deliberately free text, not an enum. A salon inventing a label it needs is not a schema change.';

create index customer_flags_org_id_idx      on public.customer_flags (org_id);
create index customer_flags_customer_id_idx on public.customer_flags (customer_id);

create trigger customer_flags_set_updated_at
  before update on public.customer_flags
  for each row execute function public.set_updated_at();

alter table public.customer_flags enable row level security;


-- ------------------------------------------------------------
-- 4. The permissions.
--
-- Four keys, and the split between them is the whole point:
--
--   customer.view            the record exists, here is the name
--   customer.manage          may create and edit
--   customer.view_sensitive  allergies, sensitivities, formulas
--   customer.view_financial  gates flags about money owed
--
-- customer.view_financial is a VISIBILITY key for a flag. It is not
-- the start of financial management, which stays out of v1. PROJECT.md
-- names "Outstanding Balance" as one of the flags the salon already
-- keeps on paper, and the requirement it states is that a stylist must
-- not see it.
-- ------------------------------------------------------------
insert into public.permissions (key, description, category) values
  ('customer.view',
   'See customer records',
   'Customers'),
  ('customer.manage',
   'Add and edit customer records',
   'Customers'),
  ('customer.view_sensitive',
   'See allergies, sensitivities and hair formulas',
   'Customers'),
  ('customer.view_financial',
   'See flags about money owed',
   'Customers')
on conflict (key) do nothing;


-- ------------------------------------------------------------
-- 5. create_organization(), redefined so a new salon starts with
-- these keys distributed sensibly.
--
-- First time receptionist and stylist get anything at all. Migration
-- 003 said their permissions would arrive with customers, and this is
-- that migration.
--
--   Receptionist  runs the front desk. Creates customers from phone
--                 calls, and is the person standing there when someone
--                 owes money. No clinical detail — a receptionist has
--                 no use for a hair formula.
--   Stylist       needs allergies before putting chemicals on someone.
--                 No financial flags, and no edit rights yet: a
--                 stylist recording their own formula is a real need
--                 and is a Phase 6 decision, not a default.
-- ------------------------------------------------------------
create or replace function public.create_organization(
  p_name      text,
  p_slug      text,
  p_timezone  text default 'Africa/Johannesburg',
  p_currency  text default 'ZAR',
  p_phone     text default null,
  p_email     text default null,
  p_address   text default null
)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  v_org_id uuid;
begin
  insert into public.organizations
    (name, slug, timezone, currency, phone, email, address)
  values
    (p_name, p_slug, p_timezone, p_currency, p_phone, p_email, p_address)
  returning id into v_org_id;

  insert into public.roles (org_id, name, display_name, is_system) values
    (v_org_id, 'owner',        'Owner',        true),
    (v_org_id, 'manager',      'Manager',      true),
    (v_org_id, 'receptionist', 'Receptionist', true),
    (v_org_id, 'stylist',      'Stylist',      true);

  -- Owner holds every permission that exists at this moment.
  insert into public.role_permissions (org_id, role_id, permission_id)
  select v_org_id, r.id, p.id
  from public.roles r
  cross join public.permissions p
  where r.org_id = v_org_id
    and r.name = 'owner';

  insert into public.role_permissions (org_id, role_id, permission_id)
  select v_org_id, r.id, p.id
  from public.roles r
  cross join public.permissions p
  where r.org_id = v_org_id
    and r.name = 'manager'
    and p.key in ('employee.manage',
                  'service.manage',
                  'employee.record.manage',
                  'customer.view',
                  'customer.manage',
                  'customer.view_sensitive',
                  'customer.view_financial');

  insert into public.role_permissions (org_id, role_id, permission_id)
  select v_org_id, r.id, p.id
  from public.roles r
  cross join public.permissions p
  where r.org_id = v_org_id
    and r.name = 'receptionist'
    and p.key in ('customer.view',
                  'customer.manage',
                  'customer.view_financial');

  insert into public.role_permissions (org_id, role_id, permission_id)
  select v_org_id, r.id, p.id
  from public.roles r
  cross join public.permissions p
  where r.org_id = v_org_id
    and r.name = 'stylist'
    and p.key in ('customer.view',
                  'customer.view_sensitive');

  return v_org_id;
end;
$$;


-- ------------------------------------------------------------
-- 6. Kedus predates all four keys, so it missed every cross join
-- above. Same shape as migration 008's backfill.
--
-- These are STARTING rows, not fixed rules. Permissions are data —
-- the owner changes who holds what by changing role_permissions, and
-- the screen for doing so arrives in Phase 6.
-- ------------------------------------------------------------
insert into public.role_permissions (org_id, role_id, permission_id)
select r.org_id, r.id, p.id
from public.roles r
cross join public.permissions p
where r.deleted_at is null
  and (
    (r.name in ('owner', 'manager')
       and p.key in ('customer.view',
                     'customer.manage',
                     'customer.view_sensitive',
                     'customer.view_financial'))
    or
    (r.name = 'receptionist'
       and p.key in ('customer.view',
                     'customer.manage',
                     'customer.view_financial'))
    or
    (r.name = 'stylist'
       and p.key in ('customer.view',
                     'customer.view_sensitive'))
  )
on conflict do nothing;


-- ------------------------------------------------------------
-- 7. Column privileges.
--
-- No grant to anon on any of the three tables. Not a restricted list —
-- nothing at all. A customer's phone number is the one piece of data
-- in this database that must never be reachable from the public site,
-- and the booking form does not need it to be: it will call a function.
--
-- Within `authenticated` the column lists are just write shape. org_id
-- is insertable and not updatable, so a row cannot be moved to another
-- salon after the fact. deleted_at is updatable and that IS the delete.
--
-- phone_digits appears in no write list because it cannot: Postgres
-- refuses to let anyone write a generated column. It is covered by the
-- table-level SELECT grant, which extends to columns added later.
-- ------------------------------------------------------------
revoke all on public.customers           from anon, authenticated;
revoke all on public.customer_care_notes from anon, authenticated;
revoke all on public.customer_flags      from anon, authenticated;

grant select on public.customers to authenticated;

grant insert (org_id, full_name, phone, email, birthday, notes,
              preferred_employee_id, first_visit_at, last_visit_at)
  on public.customers to authenticated;

grant update (full_name, phone, email, birthday, notes,
              preferred_employee_id, first_visit_at, last_visit_at,
              deleted_at)
  on public.customers to authenticated;

grant select on public.customer_care_notes to authenticated;

grant insert (org_id, customer_id, allergies, sensitivities, hair_formula)
  on public.customer_care_notes to authenticated;

grant update (allergies, sensitivities, hair_formula, deleted_at)
  on public.customer_care_notes to authenticated;

grant select on public.customer_flags to authenticated;

grant insert (org_id, customer_id, flag_type, note, created_by, min_permission)
  on public.customer_flags to authenticated;

grant update (flag_type, note, min_permission, deleted_at)
  on public.customer_flags to authenticated;


-- ------------------------------------------------------------
-- 8. Policies.
--
-- Same shape as services and employees, with one addition: reading
-- requires a permission, not just membership of the salon. On the
-- public-facing tables any member could read, because the internet
-- could already read them. Nothing about a customer is public.
-- ------------------------------------------------------------

create policy customers_select_member
  on public.customers for select to authenticated
  using (deleted_at is null
         and org_id = public.current_org_id()
         and public.has_permission('customer.view'));

create policy customers_insert
  on public.customers for insert to authenticated
  with check (org_id = public.current_org_id()
              and public.has_permission('customer.manage'));

create policy customers_update
  on public.customers for update to authenticated
  using (org_id = public.current_org_id()
         and public.has_permission('customer.manage'))
  with check (org_id = public.current_org_id());


-- Writing care notes needs BOTH keys. manage alone is the receptionist,
-- who may correct a phone number and has no business editing a formula
-- she cannot read.
create policy customer_care_notes_select
  on public.customer_care_notes for select to authenticated
  using (deleted_at is null
         and org_id = public.current_org_id()
         and public.has_permission('customer.view_sensitive'));

create policy customer_care_notes_insert
  on public.customer_care_notes for insert to authenticated
  with check (org_id = public.current_org_id()
              and public.has_permission('customer.manage')
              and public.has_permission('customer.view_sensitive'));

create policy customer_care_notes_update
  on public.customer_care_notes for update to authenticated
  using (org_id = public.current_org_id()
         and public.has_permission('customer.manage')
         and public.has_permission('customer.view_sensitive'))
  with check (org_id = public.current_org_id());


-- The flag names the permission it needs, and the policy asks for it.
-- The write policies check it too, so nobody can create or edit a flag
-- into an audience they are not in themselves.
create policy customer_flags_select
  on public.customer_flags for select to authenticated
  using (deleted_at is null
         and org_id = public.current_org_id()
         and public.has_permission('customer.view')
         and public.has_permission(min_permission));

create policy customer_flags_insert
  on public.customer_flags for insert to authenticated
  with check (org_id = public.current_org_id()
              and public.has_permission('customer.manage')
              and public.has_permission(min_permission));

create policy customer_flags_update
  on public.customer_flags for update to authenticated
  using (org_id = public.current_org_id()
         and public.has_permission('customer.manage')
         and public.has_permission(min_permission))
  with check (org_id = public.current_org_id()
              and public.has_permission(min_permission));


-- ------------------------------------------------------------
-- 9. Audit.
--
-- All three critical. This is the tier the audit log was built for —
-- PROJECT.md names customer data alongside money and permissions.
--
-- Note what this means: the audit log now holds copies of allergies
-- and formulas, in `changes`. That is correct and it is the point of
-- an audit trail. It is also why audit_log still grants SELECT to
-- nobody. When a screen for it is built, it needs a gate at least as
-- strict as customer.view_sensitive, or it becomes the back door
-- around everything in section 8.
-- ------------------------------------------------------------
create trigger customers_audit
  after insert or update on public.customers
  for each row execute function public.audit_row('customer', 'critical');

create trigger customer_care_notes_audit
  after insert or update on public.customer_care_notes
  for each row execute function public.audit_row('customer_care_note', 'critical');

create trigger customer_flags_audit
  after insert or update on public.customer_flags
  for each row execute function public.audit_row('customer_flag', 'critical');
